name: Scheduled Tasks crawlOpinetData

on:
  schedule:
    - cron: '0 0,3,7,10 * * *' # 매일 한국 시간(KST, UTC+9) 9시, 12시, 16시, 19시에 실행
  workflow_dispatch: # 수동 실행을 위한 트리거 추가

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  crawl_oil_data:
    runs-on: ubuntu-latest
    needs: run-code  # run-code 작업이 완료된 후에 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run crawl_recent_oil_data
        run: |
          python crawl_recent_oil_data.py

  crawl_lpg_data:
    runs-on: ubuntu-latest
    needs: run-code  # run-code 작업이 완료된 후에 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run crawl_recent_lpg_data
        run: |
          python crawl_recent_lpg_data.py

  configure_git:
    runs-on: ubuntu-latest
    needs: [crawl_oil_data, crawl_lpg_data]  # 두 작업이 완료된 후에 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.email "yhsofa89@gmail.com"
          git config --local user.name "GitHub Actions"

      - name: Check for changes and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN 추가
        run: |
          git add json/ # 필요한 파일 추가
          if [[ $(git diff --cached --stat) ]]; then
            echo "json/ 디렉토리 내 파일 내용 변경사항 있음"
            git commit -m "Update data files from GitHub Actions" --allow-empty
            git push
          else
            echo "No changes to commit"
          fi
